### ISSUE TITLE
This NFSS system isn't set up properly

### ISSUE THREAD

**Issue by sfo** [tud-cd/tudscr#41]
After [installing a fresh copy](https://tex.stackexchange.com/a/95373/65754) of TexLive 2019, compiling the `tudscrreprt` example from the manual (section 9.20 in version 2.06a) via `pdflatex example.tex`, I get the following error:

> ! LaTeX Error: This NFSS system isn't set up properly.

After pressing enter, the execution continues and produces a valid PDF.
Unfortunately, there is only very little information available online about this specific error message.

[Here is the full error log](https://github.com/tud-cd/tudscr/files/3385380/example.log)

**Comment by sfo** [comment]
I found the issue, sorry for the inconvenience.

**Comment by mrpiggi** [comment]
That's something, I should care about.

**Comment by gherrman** [comment]
I also had this problem with my project in Tex Live 2020. Your solution of adding babel-greek and cbfonts (I already had greek-fontenc) worked.

**Comment by mrpiggi** [comment]
As this was already fixed with v2.06b, please consider to update your distribution.

**Comment by gherrman** [comment]
I guess to add some context to my previous reply, I was just letting @sfo know that I found his solution helpful. I am using the `article` document class, and was receiving this error until I added the packages he identified. 
Tex Live 2020:
tlmgr revision 55369 (2020-06-01 02:32:00 +0200)
tlmgr using installation: C:/Users/Name/texlive/2020
TeX Live (https://tug.org/texlive) version 2020

MS VS Code:
1.45.1

Latex Workshop:
8.10.0

OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz, 2401 Mhz, 2 Core(s), 4 Logical

**Comment by Programming-Skills** [comment]
I've got this issue, I have downloded babel-greek, cbfonts and greek-fontenc but it's still not working. Any ideas?

**Comment by mrpiggi** [comment]
Probably your problem has nothing to do with the package 'tudscr', so this is probably not the right place to find help...

BTW: Providing a minimal example that reflects the bug would certainly make troubleshooting easier for volunteers and therefore significantly increase their willingness to address *your* problem.

**Comment by Pawanbhatt500** [comment]
> I found the source of my problem, sorry for any inconvenience.
> 
> Edit: The log says (just before the error message):
> 
> > No file LGRcmr.fd.
> 
> Installing the following packages resolved that issue:
> 
> * babel-greek
> * greek-fontenc
> * cbfonts

How to install these packages in texlive (I am using ubuntu)

**Comment by Pawanbhatt500** [comment]
> I've got this issue, I have downloded babel-greek, cbfonts and greek-fontenc but it's still not working. Any ideas?

Please help me to download and install these packages texlive (ubuntu). How to download and install?

**Comment by keinstein** [comment]
@Pawanbhatt500 It depends. How did you install TeXLive?
If you installed it directly from the internet `tlmgr` is the command to use (I don't use it).
If you installed texlive from the Debian Package manager, then you can search for the correct packages from the command line:
```
$ apt-cache search texlive greek
texlive-fonts-extra - TeX Live: Additional fonts
texlive-latex-extra - TeX Live: LaTeX additional packages
texlive-science - TeX Live: Mathematics, natural sciences, computer science packages
texlive-lang-european - TeX Live: Other European languages
texlive-lang-greek - TeX Live: Greek
$ apt-cache search cbfonts
texlive-lang-greek - TeX Live: Greek
$ apt-cache show texlive-lang-greek
Package: texlive-lang-greek
Source: texlive-lang
Version: 2022.20230122-1
Installed-Size: 94308
Maintainer: Debian TeX Task Force <debian-tex-maint@lists.debian.org>
Architecture: all
Depends: tex-common (>= 6.13), fonts-gfs-baskerville, fonts-gfs-porson, texlive-base (>= 2022.20220405), texlive-binaries (>= 2022.20220321)
Breaks: texlive-base (<< 2022.20220405)
Description-en: TeX Live: Greek
 Support for Greek.
 .
 This package includes the following CTAN packages:
 .
 babel-greek -- Babel support for documents written in Greek
 .
 begingreek -- Greek environment to be used with pdfLaTeX only
 .
 betababel -- Insert ancient greek text coded in Beta Code
 .
 cbfonts -- Complete set of Greek fonts
 .
 cbfonts-fd -- LaTeX font description files for the CB Greek fonts
 .
 gfsbaskerville -- A Greek font, from one such by Baskerville
 .
 gfsporson -- A Greek font, originally from Porson
 .
 greek-fontenc -- LICR macros and encoding definition files for Greek
 .
 greek-inputenc -- Greek encoding support for inputenc
 .
 greekdates -- Provides ancient Greek day and month names, dates, etc
 .
 greektex -- Fonts for typesetting Greek/English documents
 .
 greektonoi -- Facilitates writing/editing of multiaccented greek
 .
 hyphen-ancientgreek -- Ancient Greek hyphenation patterns.
 .
 hyphen-greek -- Modern Greek hyphenation patterns.
 .
 ibycus-babel -- Use the Ibycus 4 Greek font with Babel
 .
 ibygrk -- Fonts and macros to typeset ancient Greek
 .
 kerkis -- Kerkis (Greek) font family
 .
 levy -- Fonts for typesetting classical greek
 .
 lgreek -- LaTeX macros for using Silvio Levy's Greek fonts
 .
 lgrmath -- Use LGR-encoded fonts in math mode
 .
 mkgrkindex -- Makeindex working with Greek
 .
 talos -- A Greek cult font from the eighties
 .
 teubner -- Philological typesetting of classical Greek
 .
 xgreek -- Greek Language Support for XeLaTeX and LuaLaTeX
 .
 yannisgr -- Greek fonts by Yannis Haralambous
Description-md5: 2fbce88119245df736a7dd2197c01105
Multi-Arch: foreign
Homepage: http://www.tug.org/texlive/
Tag: culture::greek, role::plugin, use::chatting, use::typesetting,
 works-with-format::tex, works-with::im, works-with::text
Section: tex
Priority: optional
Filename: pool/main/t/texlive-lang/texlive-lang-greek_2022.20230122-1_all.deb
Size: 78090896
MD5sum: 0b86b354f6f3eeeb0ac435fb30f1c082
SHA256: d8ae3208b53ca5e49e21391d797036b425b4d97ba081aa70a6322978267754a5

[...]
```
As you can see, the required package is `texlive-lang-greek`. 
Please, consider also https://github.com/tud-cd/tudscr/issues/41#issuecomment-640442607 : 

> As this was already fixed with v2.06b, please consider to update your distribution.

BTW.: `tudscr` is in the package texlive-publishers.

**Comment by Pawanbhatt500** [comment]
> @Pawanbhatt500 It depends. How did you install TeXLive? If you installed it directly from the internet `tlmgr` is the command to use (I don't use it). If you installed texlive from the Debian Package manager, then you can search for the correct packages from the command line:
> 
> ```
> $ apt-cache search texlive greek
> texlive-fonts-extra - TeX Live: Additional fonts
> texlive-latex-extra - TeX Live: LaTeX additional packages
> texlive-science - TeX Live: Mathematics, natural sciences, computer science packages
> texlive-lang-european - TeX Live: Other European languages
> texlive-lang-greek - TeX Live: Greek
> $ apt-cache search cbfonts
> texlive-lang-greek - TeX Live: Greek
> $ apt-cache show texlive-lang-greek
> Package: texlive-lang-greek
> Source: texlive-lang
> Version: 2022.20230122-1
> Installed-Size: 94308
> Maintainer: Debian TeX Task Force <debian-tex-maint@lists.debian.org>
> Architecture: all
> Depends: tex-common (>= 6.13), fonts-gfs-baskerville, fonts-gfs-porson, texlive-base (>= 2022.20220405), texlive-binaries (>= 2022.20220321)
> Breaks: texlive-base (<< 2022.20220405)
> Description-en: TeX Live: Greek
>  Support for Greek.
>  .
>  This package includes the following CTAN packages:
>  .
>  babel-greek -- Babel support for documents written in Greek
>  .
>  begingreek -- Greek environment to be used with pdfLaTeX only
>  .
>  betababel -- Insert ancient greek text coded in Beta Code
>  .
>  cbfonts -- Complete set of Greek fonts
>  .
>  cbfonts-fd -- LaTeX font description files for the CB Greek fonts
>  .
>  gfsbaskerville -- A Greek font, from one such by Baskerville
>  .
>  gfsporson -- A Greek font, originally from Porson
>  .
>  greek-fontenc -- LICR macros and encoding definition files for Greek
>  .
>  greek-inputenc -- Greek encoding support for inputenc
>  .
>  greekdates -- Provides ancient Greek day and month names, dates, etc
>  .
>  greektex -- Fonts for typesetting Greek/English documents
>  .
>  greektonoi -- Facilitates writing/editing of multiaccented greek
>  .
>  hyphen-ancientgreek -- Ancient Greek hyphenation patterns.
>  .
>  hyphen-greek -- Modern Greek hyphenation patterns.
>  .
>  ibycus-babel -- Use the Ibycus 4 Greek font with Babel
>  .
>  ibygrk -- Fonts and macros to typeset ancient Greek
>  .
>  kerkis -- Kerkis (Greek) font family
>  .
>  levy -- Fonts for typesetting classical greek
>  .
>  lgreek -- LaTeX macros for using Silvio Levy's Greek fonts
>  .
>  lgrmath -- Use LGR-encoded fonts in math mode
>  .
>  mkgrkindex -- Makeindex working with Greek
>  .
>  talos -- A Greek cult font from the eighties
>  .
>  teubner -- Philological typesetting of classical Greek
>  .
>  xgreek -- Greek Language Support for XeLaTeX and LuaLaTeX
>  .
>  yannisgr -- Greek fonts by Yannis Haralambous
> Description-md5: 2fbce88119245df736a7dd2197c01105
> Multi-Arch: foreign
> Homepage: http://www.tug.org/texlive/
> Tag: culture::greek, role::plugin, use::chatting, use::typesetting,
>  works-with-format::tex, works-with::im, works-with::text
> Section: tex
> Priority: optional
> Filename: pool/main/t/texlive-lang/texlive-lang-greek_2022.20230122-1_all.deb
> Size: 78090896
> MD5sum: 0b86b354f6f3eeeb0ac435fb30f1c082
> SHA256: d8ae3208b53ca5e49e21391d797036b425b4d97ba081aa70a6322978267754a5
> 
> [...]
> ```
> 
> As you can see, the required package is `texlive-lang-greek`. Please, consider also [#41 (comment)](https://github.com/tud-cd/tudscr/issues/41#issuecomment-640442607) :
> 
> > As this was already fixed with v2.06b, please consider to update your distribution.
> 
> BTW.: `tudscr` is in the package texlive-publishers.

I installed br terminal using the command _sudo apt install texlive-latex-extra_

**Comment by keinstein** [comment]
> I installed br terminal using the command _sudo apt install texlive-latex-extra_

so you should do `sudo apt install texlive-lang-greek texlive-publishers texlive-latex-recommended texlive-fonts-recommended`

**Comment by mrpiggi** [comment]
Be aware that for most Linux distributions, including Ubuntu, the version of TeX Live is pretty sure outdated. In your case, it is TeX Live 2020 whereas 2022 is the recent version. I would really recommend to install TeX Live directly.
